GET http://localhost:3000/tasks

###
GET http://localhost:3000/users

###
GET http://localhost:3000/tasks/5fdb0e56a834421c3c97842d

###
POST http://localhost:3000/tasks
Content-Type: application/json

{
    "title": "Task One",
    "description": "Do something important!"
}

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstname": "John",
    "lastname": "Doe"
}

###
PATCH http://localhost:3000/tasks/5fdb0e56a834421c3c97842d
Content-Type: application/json

{
    "title": "Task Two"
}

###
DELETE http://localhost:3000/tasks/5fda016037a8e2341cd1aed9